<?php

namespace AppBundle\Repository;

use AppBundle\Entity\JobPosition;
use Doctrine\ORM\EntityRepository;

/**
 * JobPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobPositionRepository extends EntityRepository
{
    public function insertJob($data)
    {
        $job = new JobPosition();
        $job->setName($data['Name']);
        $job->setLink($data['Name_link']);
        $job->setCompany($data['Company']);
        $job->setLocation($data['Location']);
        $job->setEmploymentType($data['Employment_type']);
        $job->setSource($data['Source']);
        $job->setLogo($data['Logo']);
        $job->setDate(\DateTime::createFromFormat('d. m. Y', $data['Date']));

        $this->getEntityManager()->persist($job);
        $this->getEntityManager()->flush();
    }

    public function allPositions()
    {
        return parent::findBy([], null, 10);
    }
}
